### ISSUE TITLE
很奇怪 在springboot项目中引入没有成功 不知道少了什么步骤

### ISSUE THREAD

**Issue by irunmyway** [cssxsh/fix-protocol-version#1]

**Comment by cssxsh** [comment]
目前这只是 mirai console 插件

**Comment by cssxsh** [comment]
https://github.com/cssxsh/fix-protocol-version#mirai-core-%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95

**Comment by irunmyway** [comment]
> https://github.com/cssxsh/fix-protocol-version#mirai-core-%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95

能支持core-jvm版本吗，在idea springboot的方式

**Comment by irunmyway** [comment]
我的code是235的 不知道有没有办法解决，您有q吗

**Comment by cssxsh** [comment]
> 我的code是235的 不知道有没有办法解决，您有q吗

mirai-core 就是指 mirai-core-jvm 
我懒得加后缀而已
mirai-core 需要在引用jar之后 在登录之前按示例代码调用一下update方法

**Comment by irunmyway** [comment]
> > 我的code是235的 不知道有没有办法解决，您有q吗
> 
> mirai-core 就是指 mirai-core-jvm 我懒得加后缀而已 mirai-core 需要在引用jar之后 在登录之前按示例代码调用一下update方法

是的 我添加并执行了update 但是一直爆code 235 、237 提示版本过低、或者网络不稳定，我能练习您的q吗

**Comment by cssxsh** [comment]
> de 235 、237 提示版本过低、或者网络不稳定，我能练习您的q吗

这个修复插件目前是针对 `ANDROID_PHONE` 和 `ANDROID_PAD` 的
你是否是使用这两个登录协议登录

**Comment by irunmyway** [comment]
> 

是的，我几个设备类型都有使用过，效果是一样的

**Comment by cssxsh** [comment]
你可以用 `FixProtocolVersion.info`
查看一下版本信
更新之后 `ANDROID_PHONE` 和 `ANDROID_PAD` 的版本应该是 `8.9.33.10335`

**Comment by irunmyway** [comment]
确定是用的ANDROID_PHONE 确定打印出了 8.9.33.10335 确定显示了qq版本太低 code :235

**Comment by cssxsh** [comment]
> 确定是用的ANDROID_PHONE 确定打印出了 8.9.33.10335 确定显示了qq版本太低 code :235

贴你的代码

**Comment by irunmyway** [comment]
![image](https://user-images.githubusercontent.com/33797433/224271461-6da39246-7da6-4797-81e4-aafa0abe1461.png)
![image](https://user-images.githubusercontent.com/33797433/224271719-7f8e546f-a45f-48ed-bd8f-4b4a70bd8b11.png)

**Comment by cssxsh** [comment]
删了 `DeviceInfo.json`
再重新试一下
