### ISSUE TITLE
疑问：为啥IPAD协议要写成ANDROID_PAD

### ISSUE THREAD

**Issue by XiaoTong6666** [cssxsh/fix-protocol-version#15]
因为我有个手机是安卓4.4.4，所以安装的是apad，但是那个协议早几个月就寄了，tx也不再维护了，然后使用这个插件登录上去的apad其实是ipad，但是 MiraiProtocol记得是有ipad，所以为啥不直接叫ipad（

**Comment by faerfa** [comment]
安卓qq和安卓hd 合并了，现在除了appid不一样 其他的基本上一样了。
android pad apad
ios pad  ipad

**Comment by cssxsh** [comment]
不提供插件版本和协议信息，故关闭
