### ISSUE TITLE
请问您最新的fix-protocol-version1.5版本中提到的

### ISSUE THREAD

**Issue by Ezreal-y** [cssxsh/fix-protocol-version#16]
请问您最新的fix-protocol-version1.5版本中提到的mirai2.jar在哪里下载啊

**Comment by cssxsh** [comment]
![image](https://github.com/cssxsh/fix-protocol-version/assets/32539286/9b22dbb8-cac8-460a-8fc2-0433cc29c6f6)

**Comment by Ezreal-y** [comment]
> ![image](https://user-images.githubusercontent.com/32539286/238912705-9b22dbb8-cac8-460a-8fc2-0433cc29c6f6.png)

![image](https://github.com/cssxsh/fix-protocol-version/assets/49754420/369010d2-4060-47b3-af4b-ed1d8cee2a9b)
这是啥问题呢 。。

**Comment by cssxsh** [comment]
mirai 版本太老了

**Comment by Ezreal-y** [comment]
> mirai 版本太老了
![image](https://github.com/cssxsh/fix-protocol-version/assets/49754420/bba09af0-4e85-44c6-9de2-ffa527690a31)

我是在https://github.com/sonder-joker/mirai-compose/releases下载的最新的windows程序。用这个客户端登录 ，登录代码是235，按照你的项目描述，你的这个插件是启用了，但是你说我的mirai版本太老了，又没有解决这个问题。我自己创建的springboot项目中，使用mirai-login-solver-sakura 验证链接的方式 登录是code=45。

**Comment by cssxsh** [comment]
![image](https://github.com/cssxsh/fix-protocol-version/assets/32539286/461192e4-7de7-4755-b7ae-bbded749754e)
