### ISSUE TITLE
关于机器人群聊风控问题

### ISSUE THREAD

**Issue by wuchen4588** [cssxsh/fix-protocol-version#17]
![@_MIFG (16J0IPNB5@A0XD](https://github.com/cssxsh/fix-protocol-version/assets/60568101/4197a96b-030f-42eb-a527-393b0fdff7dc)
隔壁go-cqhttp给出的解决方案，希望能够更新下。

**Comment by cssxsh** [comment]
mirai 并没有处理 t544 的问题，所以只修改版本信息是没用的
