### ISSUE TITLE
SpringBoot项目引入后未生效

### ISSUE THREAD

**Issue by coldairance** [cssxsh/fix-protocol-version#2]
![image](https://user-images.githubusercontent.com/67637508/224470728-871b5588-5e5d-4d13-b4bc-e231510ffedb.png)
![image](https://user-images.githubusercontent.com/67637508/224470761-9b095228-5bf8-4ec0-a82e-670e77a7b6bc.png)
![image](https://user-images.githubusercontent.com/67637508/224471033-17c643a6-b497-431d-bac3-f486ee907db1.png)
使用的协议为 ANDROID_PHONE，此前只有通过 ANDROID_WATCH 成功，账号为新注册一个月内，仅真实登录过MacOS和IPHONE设备，请问这种该怎么解决（相关缓存都删过）

**Comment by cssxsh** [comment]
这个修复插件目前只适用来解决 `code=235`

**Comment by coldairance** [comment]
我的问题在 v1.2.0 解决，非常感谢🙏
