### ISSUE TITLE
能麻烦大佬给glibc 降个级吗？

### ISSUE THREAD

**Issue by WorldLeen** [cssxsh/fix-protocol-version#23]
出现这个报错了： libt544-enc-linux-x64.so: /lib64/libc.so.6: version `GLIBC_2.18' not found

因为目前yum最高能安装的glibc版本就是2.17
再往上更新glibc只能手动更，风险还很大，万一失败了机子就炸了
所以希望大大能否把glibc版本降到2.17呀...

**Comment by cssxsh** [comment]
不太能，用的是 Github CI 自动化，我试过最多降低版本到 ubuntu:16.04 下编译

https://github.com/LaoLittle/t544_enc/actions/runs/5239730117/jobs/9460317106?pr=1

**Comment by WorldLeen** [comment]
那好吧，没办法了
因为国内很多机器用的都是CentOS7 最高只支持到glibc 2.17
2.18恰好是不支持版本，那我只能想想办法了，谢谢

**Comment by cssxsh** [comment]
https://github.com/cssxsh/fix-protocol-version/actions/runs/5364290674

**Comment by cssxsh** [comment]
记得删一下 `libt544-enc-linux-x64.so`
