### ISSUE TITLE
引入后ABI版本不兼容，找不到类。。

### ISSUE THREAD

**Issue by afrankcat** [cssxsh/fix-protocol-version#3]
// This class file was compiled with different version of Kotlin compiler and can't be decompiled.
//
// Current compiler ABI version is 1.5.1
// File ABI version is 1.7.1

咨询下大佬，这个问题应该怎么解，掰扯好久了，，

**Comment by cssxsh** [comment]
https://github.com/cssxsh/fix-protocol-version/actions/runs/4395940525
