### ISSUE TITLE
W/fix-protocol-version: 注册服务失败，请在 2.15.0-dev-105 或更高版本下运行

### ISSUE THREAD

**Issue by Pika-Lee** [cssxsh/fix-protocol-version#33]
我下载了7.5发布的fix-protocol-version v1.8.5和unidbg-fetch-qsign-1.1.3，但是登陆的时候提示mirai版本不兼容。目前用的是2.15.0-RC，请问这个dev-105在哪里可以下载到呢？谢谢。
![QQ截图20230705210155](https://github.com/cssxsh/fix-protocol-version/assets/23114990/b096c0dd-bb3c-4818-acfb-7450cb9a1350)

**Comment by diyigemt** [comment]
https://mirai.mamoe.net/topic/2333/lapis-mirai%E5%BC%80%E5%8F%91%E7%89%88%E6%9C%AC%E4%B8%8B%E8%BD%BD%E5%99%A8

这
