### ISSUE TITLE
老是挂一段时间之后出现 sign server exit(1) ，除了遇到时重启还有别的方法解决嘛

### ISSUE THREAD

**Issue by MrY-Cat** [cssxsh/fix-protocol-version#34]
7月 06, 2023 1:49:20 下午 moe.fuqiuluo.unidbg.env.FileResolver resolve
警告: Couldn't find file: stdin
7月 06, 2023 1:49:20 下午 moe.fuqiuluo.unidbg.env.FileResolver resolve
警告: Couldn't find file: stdout
7月 06, 2023 1:49:20 下午 moe.fuqiuluo.unidbg.env.FileResolver resolve
警告: Couldn't find file: stderr
7月 06, 2023 1:49:21 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/999
7月 06, 2023 1:49:21 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/128
7月 06, 2023 1:49:21 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/10
7月 06, 2023 1:49:21 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/11
7月 06, 2023 1:49:21 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/12
7月 06, 2023 1:49:21 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/13
7月 06, 2023 1:49:21 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/14
7月 06, 2023 1:49:21 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/15
7月 06, 2023 1:49:21 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/16
7月 06, 2023 1:49:21 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/17
7月 06, 2023 1:49:21 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/18
7月 06, 2023 1:49:21 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/19
7月 06, 2023 1:49:21 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/20
7月 06, 2023 1:49:21 下午 com.github.unidbg.linux.ARM64SyscallHandler fstatat64
警告: fstatat64 dirfd=-100, pathname=D:/data/user/0/com.tencent.mobileqq/files/.system_android_l2, statbuf=RW@0x40e9d008, flags=0
7月 06, 2023 1:49:21 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/system/lib/libhoudini.so
7月 06, 2023 1:49:21 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/system/lib64/libhoudini.so
7月 06, 2023 1:49:22 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/999
7月 06, 2023 1:49:22 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/128
7月 06, 2023 1:49:22 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/10
7月 06, 2023 1:49:22 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/11
7月 06, 2023 1:49:22 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/12
7月 06, 2023 1:49:22 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/13
7月 06, 2023 1:49:22 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/14
7月 06, 2023 1:49:22 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/15
7月 06, 2023 1:49:22 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/16
7月 06, 2023 1:49:22 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/17
7月 06, 2023 1:49:22 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/18
7月 06, 2023 1:49:22 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/19
7月 06, 2023 1:49:22 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/20
7月 06, 2023 1:49:22 下午 com.github.unidbg.linux.ARM64SyscallHandler fstatat64
警告: fstatat64 dirfd=-100, pathname=D:/data/user/0/com.tencent.mobileqq/files/.system_android_l2, statbuf=RW@0x40e9d0c8, flags=0
7月 06, 2023 1:49:22 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/system/lib/libhoudini.so
7月 06, 2023 1:49:22 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/system/lib64/libhoudini.so
7月 06, 2023 1:49:22 下午 moe.fuqiuluo.unidbg.env.FileResolver resolve
警告: Couldn't find file: stdin
7月 06, 2023 1:49:22 下午 moe.fuqiuluo.unidbg.env.FileResolver resolve
警告: Couldn't find file: stdout
7月 06, 2023 1:49:22 下午 moe.fuqiuluo.unidbg.env.FileResolver resolve
警告: Couldn't find file: stderr
7月 06, 2023 1:49:23 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/999
7月 06, 2023 1:49:23 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/128
7月 06, 2023 1:49:23 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/10
7月 06, 2023 1:49:23 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/11
7月 06, 2023 1:49:23 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/12
7月 06, 2023 1:49:23 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/13
7月 06, 2023 1:49:23 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/14
7月 06, 2023 1:49:23 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/15
7月 06, 2023 1:49:23 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/16
7月 06, 2023 1:49:23 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/17
7月 06, 2023 1:49:23 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/18
7月 06, 2023 1:49:23 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/19
7月 06, 2023 1:49:23 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/20
7月 06, 2023 1:49:23 下午 com.github.unidbg.linux.ARM64SyscallHandler fstatat64
警告: fstatat64 dirfd=-100, pathname=D:/data/user/0/com.tencent.mobileqq/files/.system_android_l2, statbuf=RW@0x40e9d008, flags=0
7月 06, 2023 1:49:23 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/system/lib/libhoudini.so
7月 06, 2023 1:49:23 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/system/lib64/libhoudini.so
7月 06, 2023 1:49:24 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/999
7月 06, 2023 1:49:24 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/128
7月 06, 2023 1:49:24 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/10
7月 06, 2023 1:49:24 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/11
7月 06, 2023 1:49:24 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/12
7月 06, 2023 1:49:24 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/13
7月 06, 2023 1:49:24 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/14
7月 06, 2023 1:49:24 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/15
7月 06, 2023 1:49:24 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/16
7月 06, 2023 1:49:24 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/17
7月 06, 2023 1:49:24 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/18
7月 06, 2023 1:49:24 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/19
7月 06, 2023 1:49:24 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/data/user/20
7月 06, 2023 1:49:24 下午 com.github.unidbg.linux.ARM64SyscallHandler fstatat64
警告: fstatat64 dirfd=-100, pathname=D:/data/user/0/com.tencent.mobileqq/files/.system_android_l2, statbuf=RW@0x40e9d0c8, flags=0
7月 06, 2023 1:49:24 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/system/lib/libhoudini.so
7月 06, 2023 1:49:24 下午 com.github.unidbg.linux.ARM64SyscallHandler stat64
信息: stat64 pathname=/system/lib64/libhoudini.so
7月 06, 2023 1:49:25 下午 moe.fuqiuluo.unidbg.env.FileResolver resolve
警告: Couldn't find file: /proc/meminfo
7月 06, 2023 1:49:25 下午 com.github.unidbg.linux.ARM64SyscallHandler openat
信息: openat dirfd=-100, pathname=/proc/meminfo, oflags=0x0, mode=0
7月 06, 2023 1:49:25 下午 moe.fuqiuluo.unidbg.env.FileResolver resolve
警告: Couldn't find file: /proc/cpuinfo
7月 06, 2023 1:49:25 下午 com.github.unidbg.linux.ARM64SyscallHandler openat
信息: openat dirfd=-100, pathname=/proc/cpuinfo, oflags=0x0, mode=0
7月 06, 2023 1:49:25 下午 moe.fuqiuluo.unidbg.env.FileResolver resolve
警告: Couldn't find file: /proc/sys/kernel/random/boot_id
7月 06, 2023 1:49:25 下午 com.github.unidbg.linux.ARM64SyscallHandler openat
信息: openat dirfd=-100, pathname=/proc/sys/kernel/random/boot_id, oflags=0x0, mode=0
7月 06, 2023 1:49:25 下午 com.github.unidbg.linux.AndroidSyscallHandler getPipePair
信息: Return default pipe pair.
7月 06, 2023 1:49:25 下午 com.github.unidbg.linux.ARM64SyscallHandler fork
信息: fork
Exception in thread "DefaultDispatcher-worker-4" java.lang.IllegalStateException: running
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:352)
	at com.github.unidbg.thread.Function64.run(Function64.java:39)
	at com.github.unidbg.thread.MainTask.dispatch(MainTask.java:19)
	at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:175)
	at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:99)
	at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:340)
	at com.github.unidbg.arm.AbstractARM64Emulator.eFunc(AbstractARM64Emulator.java:236)
	at com.github.unidbg.Module.emulateFunction(Module.java:163)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:135)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethodObject(DvmObject.java:93)
	at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:48)
	at com.tencent.mobileqq.sign.QQSecuritySign.getSign$default(QQSecuritySign.kt:46)
	at moe.fuqiuluo.net.EncoderKt$buildData$1$2$sign$1.invoke(Encoder.kt:104)
	at moe.fuqiuluo.net.EncoderKt$buildData$1$2$sign$1.invoke(Encoder.kt:103)
	at moe.fuqiuluo.unidbg.QSecVMWorker.work(QSecVm.kt:26)
	at moe.fuqiuluo.unidbg.pool.FixedWorkPoolKt.work(FixedWorkPool.kt:126)
	at moe.fuqiuluo.net.EncoderKt.buildData(Encoder.kt:103)
	at moe.fuqiuluo.net.EncoderKt.encode(Encoder.kt:156)
	at moe.fuqiuluo.net.SimpleClient$initConnection$2.invokeSuspend(SimpleClient.kt:65)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(selector), StandaloneCoroutine{Cancelling}@28a809db, Dispatchers.IO]
Assertion failed!

Program: C:\Users\yang\.jdks\corretto-11.0.12\bin\java.exe
File: C:/msys64/home/Banny/git/unicorn/qemu/memory.c, Line 1329

Expression: subregion->container == mr

**Comment by mufengyan** [comment]
我也是这个问题
