### ISSUE TITLE
使用magic-signer-guide发送消息时报错

### ISSUE THREAD

**Issue by SatellaPoi** [cssxsh/fix-protocol-version#39]
<img width="1228" alt="image" src="https://github.com/cssxsh/fix-protocol-version/assets/44998959/08ba4f2c-f574-4785-a1d2-b93f2186bc2c">
发送消息期间偶现，出现此错误之后，便再无法发送消息

**Comment by cssxsh** [comment]
https://github.com/kiliokuara/magic-signer-guide/issues/5
