### ISSUE TITLE
java项目中可以指定第三方服务吗

### ISSUE THREAD

**Issue by WhiteMagic2014** [cssxsh/fix-protocol-version#41]
在本机部署了[magic-signer-guide](https://github.com/kiliokuara/magic-signer-guide)
mcl 使用 fix-protocol-version 1.9.3 + KFCFactory.json 成功登录。

现在想请问一下，用java + Mirai Core 开发bot，可以指定使用第三方的服务吗。
感谢！

**Comment by cssxsh** [comment]
也会从 KFCFactory.json 读取
