### ISSUE TITLE
每过80分钟左右，发送消息会timeout，需要重启mirai后恢复

### ISSUE THREAD

**Issue by Starlwr** [cssxsh/fix-protocol-version#44]
使用以下配置可以成功登录账号并发送消息，但是每过80分钟左右，发送消息会超时，重启 mirai 后可以继续正常发送
系统版本： Ubuntu 20.04  
Mirai版本：Mirai 2.15.0-dev-105  
签名服务：unidbg-fetch-qsign 1.1.3  
修复插件：fix-protocol-version 1.9.3  
登录协议：已尝试安卓手机和安卓平板 （8.9.63.11390）

发送消息通过 mirai-api-http，报错如下，但 mirai 本身没有异常信息输出：
![@GRD1KBA34_VA82TZX9C}I3](https://github.com/cssxsh/fix-protocol-version/assets/40411700/264f77f6-e362-4c19-8a47-98823996ded9)

同时，一个群友也遇到了同样的问题，他使用的是截止到今晚最新的版本：
系统版本： debian 11  
Mirai版本：Mirai 2.15.0 正式版  
签名服务：unidbg-fetch-qsign 1.1.3  
修复插件：fix-protocol-version 1.9.4  
登录协议：安卓平板（8.9.63.11390）

**Comment by waitsaber** [comment]
我也遇到了这个问题，一开始以为是签名服务unidbg-fetch-qsign环境不稳定问题，换成docker后也是这个问题，每次启动后大概80分钟再发送消息会提示timeout。
出现提示timeout后直接curl http://127.0.0.1:8080（qsign服务）是能正常返回值，说明qsign服务运行正常，尝试了只重启mirai可以解决发送消息提示timeout问题。
mirai暂时只有fix-protocol-verrsion调用了qsign，尝试了最新的fix-protocol-verrsion 1.9.4 也会出现这个问题。
