### ISSUE TITLE
使用本机部署的unidbg-fetch-qsign服务有时会超时，而无法自动恢复

### ISSUE THREAD

**Issue by Sunshine40** [cssxsh/fix-protocol-version#47]
第一次产生异常并打印如下错误信息后，mirai会继续运行，机器人QQ可以继续接收消息，但发送消息的时候只会静默超时500错误，也不会再次打印错误信息。

但是我重启mirai重新Autologin之后，一切又正常了，而全过程中我没有重启过unidbg-fetch-qsign服务。

> W/UnidbgFetchQsign: with CoroutineName(RequestToken)
> java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to 127.0.0.1/127.0.0.1:8963 after 30000 ms
>         at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
>         at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
>         at fix-protocol-version-1.9.4.mirai2.jar[private]//org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:201)
>         at fix-protocol-version-1.9.4.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign.requestToken(UnidbgFetchQsign.kt:79)
>         at fix-protocol-version-1.9.4.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign.access$requestToken(UnidbgFetchQsign.kt:12)
>         at fix-protocol-version-1.9.4.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign$qSecurityGetSign$1.invokeSuspend(UnidbgFetchQsign.kt:121)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
> Caused by: java.util.concurrent.TimeoutException: Request timeout to 127.0.0.1/127.0.0.1:8963 after 30000 ms
>         at fix-protocol-version-1.9.4.mirai2.jar[private]//org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
>         at fix-protocol-version-1.9.4.mirai2.jar[private]//org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50)
>         at fix-protocol-version-1.9.4.mirai2.jar[private]//io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
>         at fix-protocol-version-1.9.4.mirai2.jar[private]//io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
>         at fix-protocol-version-1.9.4.mirai2.jar[private]//io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
>         at fix-protocol-version-1.9.4.mirai2.jar[private]//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
>         at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by cssxsh** [comment]
https://github.com/cssxsh/fix-protocol-version/discussions/45
