### ISSUE TITLE
使用系统代理的选项开启后无法关闭

### ISSUE THREAD

**Issue by tanfond** [cssxsh/fix-protocol-version#55]
[mirai#2733](https://github.com/mamoe/mirai/issues/2733)

**Comment by tanfond** [comment]
FixProtocolVersion.load 不会出现这个问题，暂时先使用了 FixProtocolVersion.load

**Comment by tanfond** [comment]
FixProtocolVersion.load 没有出现这样的问题，暂时使用的 FixProtocolVersion.load

**Comment by cssxsh** [comment]
https://github.com/cssxsh/fix-protocol-version/blob/12d9a0d2bb9e48ca8b017bc025b49c88aab0913f/src/main/kotlin/xyz/cssxsh/mirai/tool/FixProtocolVersion.kt#L263-L271

**Comment by cssxsh** [comment]
1. System.setProperty("java.net.useSystemProxies", system)  无效
2. 你的系统代理有问题

加在一起炸掉了mirai 的上传请求

**Comment by cssxsh** [comment]
另外 FixProtocolVersion.sync 会直接同步从 https://github.com/RomiChan/protocol-versions 得到的最新版协议
而签名服务和协议版本要相互匹配，一旦协议变更，坐等 code=45

**Comment by tanfond** [comment]
代理似乎没有问题，我测试了如下代码：
```java
            Proxy proxy;
            try {
                System.setProperty("java.net.useSystemProxies", "true");
                List<Proxy> proxyList = ProxySelector.getDefault().select(new URI("https://www.google.com/"));
                proxy = proxyList.size() > 0 ? proxyList.get(0) : Proxy.NO_PROXY;
            } catch (URISyntaxException e) {
                proxy = Proxy.NO_PROXY;
                e.printStackTrace();
            } finally {
                System.setProperty("java.net.useSystemProxies", systemProxy);
            }
            sj.add("proxy = " + proxy.toString());
            sj.add("systemProxies = " + systemProxy);
```
打印输出结果：
```
proxy = HTTP @ 127.0.0.1:10809
systemProxies = false
```

**Comment by tanfond** [comment]
我的代理使用的是 v2rayN 的 自动配置系统代理 和 自定义路由规则

**Comment by tanfond** [comment]
问个题外话：sync 可不可以改成 FixProtocolVersion 优先从 KFCFactory.json 配置了签名服务器的版本中 匹配 协议.json 文件？
如果  KFCFactory.json 如果启用了 KFCFactory.install() 并且没有找到对应的 协议.json 文件则抛出异常，从而避免 协议变更，坐等 code=45。如果匹配到的 协议.json 不是最新的则提示最新的协议版本
