### ISSUE TITLE
code=45，在newBot之前，调用了FixProtocolVersion.update()，但是日志中没有打印任何和签名服务交互的日志

### ISSUE THREAD

**Issue by sadtrain** [cssxsh/fix-protocol-version#56]
mirai版本2.15.0正式版
fix-protocol-version 1.9.4
本地搭建的unidbg-fetch-qsign服务为1.1.4
操作系统：Windows server2022

        botConfiguration.setProtocol(BotConfiguration.MiraiProtocol.ANDROID_PHONE);
        FixProtocolVersion.update(); 
        Bot myBot = instance.newBot(botNum, password, botConfiguration);

**Comment by sadtrain** [comment]
求助，是代码执行顺序不对吗？还是我的用法错误？
看日志中没有任何关于和签名服务unidbg-fetch-qsign交互的日志

**Comment by cssxsh** [comment]
`FixProtocolVersion.update` 从 FixProtocolVersion 本身的代码升级协议
`FixProtocolVersion.sync` 从上游项目 https://github.com/RomiChan/protocol-versions 同步协议
`FixProtocolVersion.load` 从本地文件拉取协议

**Comment by yoonching** [comment]
你是想用三方签名吧，需要KFCFactory.json的那个？
那你可能还需要加一条指令，在你newBot之前加KFCFactory.install() 

这时如果又出现了依赖问题就需要加个包，例如在build.gradle.kts需要加一条
implementation("org.asynchttpclient:async-http-client:2.12.3")

希望对你有用

**Comment by yoonching** [comment]
成功后你还是会需要滑块，但是增加签名后日志特别多，注意日志滚动别把滑块那错过去了。
