### ISSUE TITLE
这是针对服主还是开发者的暂时修复协议包？

### ISSUE THREAD

**Issue by Tanloon** [cssxsh/fix-protocol-version#6]
我是从MiraiMc那边过来的，
请问下修复步骤是这样子吗：
1. 关闭服务器
2. 把这个fix-protocol-version-1.3.0.mirai2.jar包放到服务器的server/plugins中
3. 删除server/plugins/MiraiMC/MiraiBot/bots/QQ号/device.json
4. 启动服务器
我在启动日志中没看到_Mirai版本低于预期，将升级协议版本_这几个字眼，登录也依旧提示235
![image](https://user-images.githubusercontent.com/28031087/225183343-39d2b94f-b225-4a7e-9ef4-281dcd257110.png)

还是说需要自己开发，引用这个jar包，调用其api来修复qq登录提示235的问题？

感谢回复

**Comment by cssxsh** [comment]
?

**Comment by Tanloon** [comment]
？这不是用来修复Mirai目前出现登录235的问题的？

**Comment by cssxsh** [comment]
> ？这不是用来修复Mirai目前出现登录235的问题的？

是用来修复Mirai的
但是不能直接在 MiraiMC 里直接用

**Comment by Cobyqwq** [comment]
> > ？这不是用来修复Mirai目前出现登录235的问题的？
> 
> 是用来修复Mirai的 但是不能直接在 MiraiMC 里直接用

我也遇到了问题，请问一下现在MiraiMC如何修复？

**Comment by liuqianpan2008** [comment]
> 我是从MiraiMc那边过来的， 请问下修复步骤是这样子吗：
> 
> 1. 关闭服务器
> 2. 把这个fix-protocol-version-1.3.0.mirai2.jar包放到服务器的server/plugins中
> 3. 删除server/plugins/MiraiMC/MiraiBot/bots/QQ号/device.json
> 4. 启动服务器
>    我在启动日志中没看到_Mirai版本低于预期，将升级协议版本_这几个字眼，登录也依旧提示235
>    ![image](https://user-images.githubusercontent.com/28031087/225183343-39d2b94f-b225-4a7e-9ef4-281dcd257110.png)
> 
> 还是说需要自己开发，引用这个jar包，调用其api来修复qq登录提示235的问题？
> 
> 感谢回复

请虔诚的跪在电脑前请求神帮你解决
