### ISSUE TITLE
请求适配8.98.63、8.98.68、8.98.70协议

### ISSUE THREAD

**Issue by willyautoman** [cssxsh/fix-protocol-version#62]
隔壁[fuqiuluo](https://github.com/fuqiuluo)
/
[unidbg-fetch-qsign](https://github.com/fuqiuluo/unidbg-fetch-qsign)的协议已经适配至8.9.63、8.9.68、8.9.70，且仓库里已没有8.9.58的相关配置文件。但fix-protocol-version目前仅支持到8.9.58，希望可以尽快适配，谢谢

**Comment by mikko-mikust** [comment]
63.68.70协议都pr有了，68/70协议的json你要去https://github.com/RomiChan/protocol-versions
下载,插件使用的协议都可以自己导入，~~当然还是先看懂md比较好~~
