### ISSUE TITLE
签名服务只配备一个不能使用吗

### ISSUE THREAD

**Issue by when4t** [cssxsh/fix-protocol-version#65]
fuqiuluo/unidbg-fetch-qsign正常配备并确定能使用，修改了KFCFactory.json删除了kiliokuara/magic-signer-guide的配置后提示
![image](https://github.com/cssxsh/fix-protocol-version/assets/128164304/9224e5c6-82f7-42d0-b560-71aacd83e2de)
有没有解决方法啊

**Comment by cssxsh** [comment]
- 没有协议版本信息
- 没有 fuqiuluo/unidbg-fetch-qsign 版本信息

**Comment by mikko-mikust** [comment]
这个是json解析错误,应该是你的KFCFactory.json问题

**Comment by when4t** [comment]
又看了下，提示 W/KFCFactory: 请更新 unidbg-fetch-qsign 我是用的一键部署
![image](https://github.com/cssxsh/fix-protocol-version/assets/128164304/25f8d302-253a-43a6-ba0d-2806fd49c757)
