### ISSUE TITLE
[Need Help] 出现风控code=45时，切换到MACOS协议又会出现code=235，提示版本过低

### ISSUE THREAD

**Issue by HatsuneMK00** [cssxsh/fix-protocol-version#7]
在3月14日时，通过fix-protocol-version==1.2.0解决了code=45的问题，将协议设置为了MACOS，但是今天（3月17日）通过mcl登录时，提示code=235，版本过低。在Aoki上登录同样也提示code=235，并且根据指引尝试了在手机官方客户端登录，仍然没有解决。

我看到fix-protocol-version中MACOS协议的版本是2020年，不知道和这个是否有关？

感谢项目的开发与维护！

**Comment by HatsuneMK00** [comment]
我在Mirai上登录时删除了`bots/<qq_number>/`目录下的所有内容，包括device.json；
切换到ANDROID_PAD协议后登录，此时提示需要滑动验证码；
在网页完成验证码后将ticket复制回mcl命令行程序中，此时一定会报错code=45.

我使用的是Linux的纯命令行版本，因此现在情况是如果使用MACOS协议，会报错code=235，使用ANDROID相关协议，则会因为验证码问题报错code=45。（此前code=45是通过Aoki上登录，然后将device.json复制到linux服务器上，以及使用MACOS协议解决的）

另外，在Aoki上，不论切换什么协议，都报错code=235。不确定这个是否存在问题？

**Comment by cssxsh** [comment]
首先 你提供的信息混乱
我并不知道你到底你的具体操作流程和结果的关联
比如我不知道 你的 `code=235` 是出现在 mirai-console 还是 aoki

其次我不知道你的 Aoki 是什么版本，你最好升级到最新版
还有在 Aoki 上登录也要清除 device，不然依旧会 235

**Comment by HatsuneMK00** [comment]
在Aoki上使用任何协议都会235，在mirai-console上只有使用MACOS协议会235.
Aoki是最新版，并且也清除了device.json

我想问下正常情况下，如果MACOS上触发了235，切换到ANDROID_PAD后应该是不会出现235吧？还是说我必须在mac上用新的客户端登录了出现235的账号才有可能消掉这个code？

**Comment by cssxsh** [comment]
你依然没有提供具体的  `Aoki` 版本号

而且  `Aoki` 登录也不是必须的, 我不知道你为什么老是强调 `Aoki`

用 https://github.com/KasukuSakura/mirai-login-solver-sakura 处理验证 也是一种选择

**Comment by cssxsh** [comment]
我目前的建议是不要使用 `Aoki`, 因为它生成的 device 信息的特征可能已经被腾讯拉黑了
 （仅限你的手上的那个，因为他是根据物理机子生成的）

你可以试试 https://github.com/cssxsh/mirai-device-generator 这个插件
然后配合 https://github.com/KasukuSakura/mirai-login-solver-sakura 解决滑块
