### ISSUE TITLE
最新的就是8.9.63吗?

### ISSUE THREAD

**Issue by xingchenxuup** [cssxsh/fix-protocol-version#70]
FixProtocolVersion.fetch(BotConfiguration.MiraiProtocol.ANDROID_PHONE, "latest"); 获取的是8.9.63.11390

**Comment by cssxsh** [comment]
https://github.com/cssxsh/fix-protocol-version/blob/b5859e1dfac8c08cf49f8b604fbef21c0965e791/README.md?plain=1#L146
