### ISSUE TITLE
项目上怎么配置签名服务器？

### ISSUE THREAD

**Issue by KUDI139** [cssxsh/fix-protocol-version#73]
这两个问题实在不知道怎么解决

[arch2023-08-13.log](https://github.com/cssxsh/mirai-hibernate-http/files/12329045/arch2023-08-13.log)
![{6D40CC55-3489-493c-8798-B0DCCC252A9E}](https://github.com/cssxsh/mirai-hibernate-http/assets/95287528/09049617-fb26-4cf9-a187-55efd0a5af6b)

**Comment by cssxsh** [comment]
https://github.com/cssxsh/fix-protocol-version#mirai-core-%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95
