### ISSUE TITLE
在idea中可以正常运行，打包后使用java -jar启动提示Bot verify info [xxx] registration failed or start failed错误

### ISSUE THREAD

**Issue by keithfeng425** [cssxsh/fix-protocol-version#74]
导入的jar包为fix-protocol-version-1.10.0.mirai2.jar，使用签名服务器为unidbg-fetch-qsign-1.1.7，在idea中运行毫无问题：
![image](https://github.com/cssxsh/fix-protocol-version/assets/36266938/bbed001d-705c-4279-83a8-d04f7f7a70d7)

通过maven进行package后，独立运行jar包出现如下报错：
![image](https://github.com/cssxsh/fix-protocol-version/assets/36266938/f8f0a957-65d3-4c79-8fbd-9abf0e940e73)
![image](https://github.com/cssxsh/fix-protocol-version/assets/36266938/8d5f1ebf-ec00-40ac-a074-abcb0f866c14)

请问这是什么原因导致的呢？

**Comment by cssxsh** [comment]
不知道
这看起来和我的插件没有关系

而且你这也不是原版 mirai
