### ISSUE TITLE
增加对Shamrock的签名支持

### ISSUE THREAD

**Issue by Xiaolangs** [cssxsh/fix-protocol-version#84]
### 特性描述

https://github.com/linxinrao/Shamrock
基与Xposed实现的提供了相关的sign，但[fix-protocol-version](https://github.com/cssxsh/fix-protocol-version) 不兼容

**Comment by cssxsh** [comment]
大概不行，登录会话和签名应该是相互绑定的

**Comment by linxinrao** [comment]
shamrock提供了**获取当前被hook的QQAPP中已经登陆了的账号**的api，可以基于这个做一个判断是否允许某个QQ账号去调用sign签名。
基于shamrock实现的签名服务更加稳定安全，同时条件也很苛刻。
