### ISSUE TITLE
适配shamrock作为签名服务器

### ISSUE THREAD

**Issue by 502milk** [cssxsh/fix-protocol-version#89]
项目连接[https://github.com/linxinrao/Shamrock](https://github.com/linxinrao/Shamrock)

**Comment by shinelouis** [comment]
> 项目连接https://github.com/linxinrao/Shamrock

请问下，Shamrock的签名文档说，已支持的框架是icqq和gocq，mirai对接API是否也方便？看了下gocq置顶的issue，也说未来趋势是Hook官方客户端，而不是协议库了。要做好慢慢迁移的准备。

**Comment by 502milk** [comment]
他们说是这边兼容一下就好了
现在不少人正在研究docker跑安卓镜像来使用
现在还能跑的，尽量就不要动了

**Comment by cssxsh** [comment]
https://github.com/cssxsh/fix-protocol-version/issues/84
