### ISSUE TITLE
我想问一下 protocol-versions 的来源是什么

### ISSUE THREAD

**Issue by CaiJingLong** [cssxsh/fix-protocol-version#90]
版本信息的上游仓库很久没有更新了 https://github.com/RomiChan/protocol-versions
这个有关版本的json文件/信息要如何提取？
有没有工具/文档/说明

**Comment by cssxsh** [comment]
https://github.com/RomiChan/protocol-versions/pulls

**Comment by CaiJingLong** [comment]
我看到这里只有成品，比如我希望可以自行提取 8.9.83 版本的对应的 android_phone/8.9.83.json
我应该怎么做？

**Comment by DINOREXNB** [comment]
> 我看到这里只有成品，比如我希望可以自行提取 8.9.83 版本的对应的 android_phone/8.9.83.json 我应该怎么做？

https://github.com/MrXiaoM/Eden
通过这个获取config.json
